/**
 * Static venue data for World Cup 2026.
 * All 16 official stadiums across USA, Canada, and Mexico.
 * Source: FIFA official WC 2026 host venues.
 */

export interface WCVenue {
  id: string;
  name: string;
  city: string;
  country: 'USA' | 'Canada' | 'Mexico';
  flag: string;
  capacity: number;
  surface: string;
  lat: number;
  lng: number;
  image?: string;
  matchesHosted?: number; // planned WC matches
}

export const WC_VENUES: WCVenue[] = [
  // USA
  {
    id: 'metlife',
    name: 'MetLife Stadium',
    city: 'East Rutherford, NJ',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 82_500,
    surface: 'FieldTurf',
    lat: 40.8135,
    lng: -74.0745,
    matchesHosted: 8,
  },
  {
    id: 'sofi',
    name: 'SoFi Stadium',
    city: 'Inglewood, CA',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 70_240,
    surface: 'FieldTurf',
    lat: 33.9535,
    lng: -118.3392,
    matchesHosted: 7,
  },
  {
    id: 'att',
    name: "AT&T Stadium",
    city: 'Arlington, TX',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 80_000,
    surface: 'AstroTurf',
    lat: 32.7480,
    lng: -97.0930,
    matchesHosted: 7,
  },
  {
    id: 'levis',
    name: "Levi's Stadium",
    city: 'Santa Clara, CA',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 68_500,
    surface: 'Natural grass',
    lat: 37.4032,
    lng: -121.9697,
    matchesHosted: 7,
  },
  {
    id: 'lincoln-financial',
    name: 'Lincoln Financial Field',
    city: 'Philadelphia, PA',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 69_796,
    surface: 'Natural grass',
    lat: 39.9008,
    lng: -75.1675,
    matchesHosted: 7,
  },
  {
    id: 'hard-rock',
    name: 'Hard Rock Stadium',
    city: 'Miami Gardens, FL',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 65_326,
    surface: 'Natural grass',
    lat: 25.9580,
    lng: -80.2389,
    matchesHosted: 7,
  },
  {
    id: 'nrg',
    name: 'NRG Stadium',
    city: 'Houston, TX',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 72_220,
    surface: 'Natural grass',
    lat: 29.6847,
    lng: -95.4107,
    matchesHosted: 7,
  },
  {
    id: 'arrowhead',
    name: 'Arrowhead Stadium',
    city: 'Kansas City, MO',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 76_416,
    surface: 'Natural grass',
    lat: 39.0489,
    lng: -94.4839,
    matchesHosted: 7,
  },
  {
    id: 'seattle',
    name: 'Lumen Field',
    city: 'Seattle, WA',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 69_000,
    surface: 'FieldTurf',
    lat: 47.5952,
    lng: -122.3316,
    matchesHosted: 7,
  },
  {
    id: 'boston',
    name: 'Gillette Stadium',
    city: 'Foxborough, MA',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 65_878,
    surface: 'Natural grass',
    lat: 42.0909,
    lng: -71.2643,
    matchesHosted: 7,
  },
  {
    id: 'atlanta',
    name: 'Mercedes-Benz Stadium',
    city: 'Atlanta, GA',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 71_000,
    surface: 'FieldTurf',
    lat: 33.7554,
    lng: -84.4009,
    matchesHosted: 7,
  },
  // Canada
  {
    id: 'bmo',
    name: 'BMO Field',
    city: 'Toronto, ON',
    country: 'Canada',
    flag: '🇨🇦',
    capacity: 30_000,
    surface: 'Natural grass',
    lat: 43.6333,
    lng: -79.4189,
    matchesHosted: 7,
  },
  {
    id: 'bc-place',
    name: 'BC Place',
    city: 'Vancouver, BC',
    country: 'Canada',
    flag: '🇨🇦',
    capacity: 54_500,
    surface: 'FieldTurf',
    lat: 49.2767,
    lng: -123.1119,
    matchesHosted: 7,
  },
  // Mexico
  {
    id: 'azteca',
    name: 'Estadio Azteca',
    city: 'Mexico City',
    country: 'Mexico',
    flag: '🇲🇽',
    capacity: 87_523,
    surface: 'Natural grass',
    lat: 19.3029,
    lng: -99.1503,
    matchesHosted: 7,
  },
  {
    id: 'guadalajara',
    name: 'Estadio Akron',
    city: 'Zapopan, Jalisco',
    country: 'Mexico',
    flag: '🇲🇽',
    capacity: 49_850,
    surface: 'Natural grass',
    lat: 20.7149,
    lng: -103.4029,
    matchesHosted: 7,
  },
  {
    id: 'monterrey',
    name: 'Estadio BBVA',
    city: 'Guadalupe, Nuevo León',
    country: 'Mexico',
    flag: '🇲🇽',
    capacity: 53_500,
    surface: 'Natural grass',
    lat: 25.6692,
    lng: -100.2585,
    matchesHosted: 7,
  },
];
